module Bullet
  VERSION: String

  class Error < StandardError
  end

  class Vector3
    attr_accessor x: Float
    attr_accessor y: Float
    attr_accessor z: Float

    def self.zero: () -> Vector3
    def self.coerce: (Vector3 | [Numeric, Numeric, Numeric]) -> Vector3

    def initialize: (?Numeric x, ?Numeric y, ?Numeric z) -> void
    def []: (Integer index) -> Float
    def []=: (Integer index, Numeric value) -> Numeric
    def +: (Vector3 | [Numeric, Numeric, Numeric] other) -> Vector3
    def -: (Vector3 | [Numeric, Numeric, Numeric] other) -> Vector3
    def -@: () -> Vector3
    def *: (Numeric scalar) -> Vector3
    def /: (Numeric scalar) -> Vector3
    def length: () -> Float
    def length2: () -> Float
    def normalize: () -> Vector3
    def normalize!: () -> Vector3
    def normalized: () -> Vector3
    def dot: (Vector3 | [Numeric, Numeric, Numeric] other) -> Float
    def cross: (Vector3 | [Numeric, Numeric, Numeric] other) -> Vector3
    def distance: (Vector3 | [Numeric, Numeric, Numeric] other) -> Float
    def distance2: (Vector3 | [Numeric, Numeric, Numeric] other) -> Float
    def lerp: (Vector3 | [Numeric, Numeric, Numeric] other, Numeric t) -> Vector3
    def angle: (Vector3 | [Numeric, Numeric, Numeric] other) -> Float
    def absolute: () -> Vector3
    def to_a: () -> [Float, Float, Float]
  end

  class Quaternion
    attr_accessor x: Float
    attr_accessor y: Float
    attr_accessor z: Float
    attr_accessor w: Float

    def self.identity: () -> Quaternion
    def self.from_axis_angle: (Vector3 | [Numeric, Numeric, Numeric] axis, Numeric angle) -> Quaternion
    def self.from_euler: (Numeric roll, Numeric pitch, Numeric yaw) -> Quaternion
    def self.coerce: (Quaternion | [Numeric, Numeric, Numeric, Numeric]) -> Quaternion

    def initialize: (?Numeric x, ?Numeric y, ?Numeric z, ?Numeric w) -> void
    def *: (Quaternion | [Numeric, Numeric, Numeric, Numeric] other) -> Quaternion
    def inverse: () -> Quaternion
    def angle: () -> Float
    def axis: () -> Vector3
    def slerp: (Quaternion | [Numeric, Numeric, Numeric, Numeric] other, Numeric t) -> Quaternion
    def to_euler: () -> [Float, Float, Float]
    def to_matrix: () -> Matrix3x3
    def normalized: () -> Quaternion
    def to_a: () -> [Float, Float, Float, Float]
  end

  class Matrix3x3
    def self.identity: () -> Matrix3x3
    def self.from_quaternion: (Quaternion | [Numeric, Numeric, Numeric, Numeric] quaternion) -> Matrix3x3

    def initialize: (?Numeric xx, ?Numeric xy, ?Numeric xz, ?Numeric yx, ?Numeric yy, ?Numeric yz, ?Numeric zx, ?Numeric zy, ?Numeric zz) -> void
    def *: (Vector3 | [Numeric, Numeric, Numeric] vector) -> Vector3
    def transpose: () -> Matrix3x3
    def to_a: () -> [[Float, Float, Float], [Float, Float, Float], [Float, Float, Float]]
  end

  class Transform
    attr_accessor origin: Vector3
    attr_accessor rotation: Quaternion

    def self.identity: () -> Transform

    def initialize: (?Quaternion | [Numeric, Numeric, Numeric, Numeric] rotation, ?Vector3 | [Numeric, Numeric, Numeric] origin) -> void
    def basis: () -> Matrix3x3
    def *: (Transform | Vector3 other) -> (Transform | Vector3)
    def inverse: () -> Transform
    def inverse_times: (Transform other) -> Transform
    def to_a: () -> [[Float, Float, Float], [Float, Float, Float, Float]]
  end

  module Shapes
    class CollisionShape
      def shape_type: () -> Symbol
      def local_scaling: () -> Vector3
      def local_scaling=: (Vector3 | [Numeric, Numeric, Numeric] scaling) -> Vector3
      def margin: () -> Float
      def margin=: (Numeric margin) -> Numeric
      def calculate_local_inertia: (Numeric mass) -> Vector3
      def bounding_sphere: () -> [Vector3, Float]
    end

    class BoxShape < CollisionShape
      def initialize: (Vector3 half_extents) -> void
    end

    class SphereShape < CollisionShape
      def initialize: (Numeric radius) -> void
    end

    class CapsuleShape < CollisionShape
      def initialize: (Numeric radius, Numeric height) -> void
    end

    class CylinderShape < CollisionShape
      def initialize: (Vector3 half_extents) -> void
    end

    class ConeShape < CollisionShape
      def initialize: (Numeric radius, Numeric height) -> void
    end

    class StaticPlaneShape < CollisionShape
      def initialize: (Vector3 normal, Numeric offset) -> void
    end
  end

  class CollisionConfiguration
    def initialize: () -> void
  end

  class CollisionDispatcher
    def initialize: (CollisionConfiguration configuration) -> void
  end

  class DbvtBroadphase
    def initialize: () -> void
  end

  class SequentialImpulseConstraintSolver
    def initialize: () -> void
  end

  class MotionState
    attr_accessor world_transform: Transform

    def initialize: (?Transform start_transform) -> void
  end

  class RigidBodyConstructionInfo
    def initialize: (Numeric mass, MotionState motion_state, Shapes::CollisionShape collision_shape, ?Vector3 | [Numeric, Numeric, Numeric] local_inertia) -> void
    def mass: () -> Float
    def local_inertia: () -> Vector3
    def friction: () -> Float
    def friction=: (Numeric friction) -> Numeric
    def restitution: () -> Float
    def restitution=: (Numeric restitution) -> Numeric
  end

  class RigidBody
    def initialize: (RigidBodyConstructionInfo construction_info) -> void
    def mass: () -> Float
    def collision_shape: () -> Shapes::CollisionShape
    def world_transform: () -> Transform
    def world_transform=: (Transform transform) -> Transform
    def linear_velocity: () -> Vector3
    def linear_velocity=: (Vector3 | [Numeric, Numeric, Numeric] velocity) -> Vector3
    def angular_velocity: () -> Vector3
    def angular_velocity=: (Vector3 | [Numeric, Numeric, Numeric] velocity) -> Vector3
    def total_force: () -> Vector3
    def total_torque: () -> Vector3
    def friction: () -> Float
    def friction=: (Numeric friction) -> Numeric
    def restitution: () -> Float
    def restitution=: (Numeric restitution) -> Numeric
    def damping: () -> [Float, Float]
    def set_damping: (Numeric linear_damping, Numeric angular_damping) -> [Float, Float]
    def apply_central_force: (Vector3 | [Numeric, Numeric, Numeric] force) -> void
    def apply_force: (Vector3 | [Numeric, Numeric, Numeric] force, Vector3 | [Numeric, Numeric, Numeric] relative_position) -> void
    def apply_torque: (Vector3 | [Numeric, Numeric, Numeric] torque) -> void
    def apply_central_impulse: (Vector3 | [Numeric, Numeric, Numeric] impulse) -> void
    def apply_impulse: (Vector3 | [Numeric, Numeric, Numeric] impulse, Vector3 | [Numeric, Numeric, Numeric] relative_position) -> void
    def clear_forces: () -> void
    def activate: () -> void
    def active?: () -> bool
    def static?: () -> bool
    def kinematic?: () -> bool
  end

  class DiscreteDynamicsWorld
    def self.create: () -> DiscreteDynamicsWorld

    def initialize: () -> void
                  | (CollisionDispatcher dispatcher, DbvtBroadphase broadphase, SequentialImpulseConstraintSolver solver, CollisionConfiguration configuration) -> void
    def gravity: () -> Vector3
    def gravity=: (Vector3 | [Numeric, Numeric, Numeric] gravity) -> Vector3
    def add_rigid_body: (RigidBody rigid_body) -> void
    def remove_rigid_body: (RigidBody rigid_body) -> void
    def step_simulation: (Numeric time_step, ?Integer max_sub_steps, ?Numeric fixed_time_step) -> Integer
    def num_collision_objects: () -> Integer
    def clear_forces: () -> void
    def synchronize_motion_states: () -> void
  end
end

module BulletRuby
  VERSION: String
  Error: singleton(Bullet::Error)
end
